# https://taskfile.dev

version: '3'

vars:
  CURL_VERSION: '{{.CURL_VERSION | default "7.83.1"}}'
  
  PROJECT_NAME: curl
  REGISTRY_SERVER: public.ecr.aws/u4i8g9e8
  REGISTRY: '{{.REGISTRY_SERVER}}/{{.PROJECT_NAME}}'

tasks:
  default:
    cmds:
      - task: buildx
    silent: true

  buildx:
    cmds:
      - |-
        docker buildx build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --build-arg CURL_VERSION={{.CURL_VERSION}} \
        --platform linux/amd64,linux/arm64 \
        --target builder \
        -t {{.REGISTRY}}:builder-{{.CURL_VERSION}} \
        -t {{.REGISTRY}}:builder-latest \
        --cache-from={{.REGISTRY}}:builder-{{.CURL_VERSION}} \
        --push \
        .
      
      - |-
        docker buildx build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --build-arg CURL_VERSION={{.CURL_VERSION}} \
        --platform linux/amd64,linux/arm64 \
        -t {{.REGISTRY}}:{{.CURL_VERSION}} \
        -t {{.REGISTRY}}:latest \
        --cache-from={{.REGISTRY}}:builder-{{.CURL_VERSION}} \
        --push \
        .
